package vn.bananavietnam.ict.common.db.model;

public class IvbMStatusKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_STATUS.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_STATUS.STATUS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String statusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_STATUS.FARM_ID
     *
     * @return the value of IVB_M_STATUS.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_STATUS.FARM_ID
     *
     * @param farmId the value for IVB_M_STATUS.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setFarmId(String farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_STATUS.STATUS_ID
     *
     * @return the value of IVB_M_STATUS.STATUS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_STATUS.STATUS_ID
     *
     * @param statusId the value for IVB_M_STATUS.STATUS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }
}