package vn.bananavietnam.ict.common.db.model;

public class IvbMManagerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_MANAGER.USERS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_MANAGER.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_MANAGER.AREA_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String areaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_MANAGER.USERS_ID
     *
     * @return the value of IVB_M_MANAGER.USERS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_MANAGER.USERS_ID
     *
     * @param usersId the value for IVB_M_MANAGER.USERS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setUsersId(String usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_MANAGER.FARM_ID
     *
     * @return the value of IVB_M_MANAGER.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_MANAGER.FARM_ID
     *
     * @param farmId the value for IVB_M_MANAGER.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setFarmId(String farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_MANAGER.AREA_ID
     *
     * @return the value of IVB_M_MANAGER.AREA_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_MANAGER.AREA_ID
     *
     * @param areaId the value for IVB_M_MANAGER.AREA_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }
}