package vn.bananavietnam.ict.common.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class IvbMFarmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public IvbMFarmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andFarmIdIsNull() {
            addCriterion("FARM_ID is null");
            return (Criteria) this;
        }

        public Criteria andFarmIdIsNotNull() {
            addCriterion("FARM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFarmIdEqualTo(String value) {
            addCriterion("FARM_ID =", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotEqualTo(String value) {
            addCriterion("FARM_ID <>", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdGreaterThan(String value) {
            addCriterion("FARM_ID >", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdGreaterThanOrEqualTo(String value) {
            addCriterion("FARM_ID >=", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdLessThan(String value) {
            addCriterion("FARM_ID <", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdLessThanOrEqualTo(String value) {
            addCriterion("FARM_ID <=", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdLike(String value) {
            addCriterion("FARM_ID like", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotLike(String value) {
            addCriterion("FARM_ID not like", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdIn(List<String> values) {
            addCriterion("FARM_ID in", values, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotIn(List<String> values) {
            addCriterion("FARM_ID not in", values, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdBetween(String value1, String value2) {
            addCriterion("FARM_ID between", value1, value2, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotBetween(String value1, String value2) {
            addCriterion("FARM_ID not between", value1, value2, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmNameIsNull() {
            addCriterion("FARM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFarmNameIsNotNull() {
            addCriterion("FARM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFarmNameEqualTo(String value) {
            addCriterion("FARM_NAME =", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameNotEqualTo(String value) {
            addCriterion("FARM_NAME <>", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameGreaterThan(String value) {
            addCriterion("FARM_NAME >", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameGreaterThanOrEqualTo(String value) {
            addCriterion("FARM_NAME >=", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameLessThan(String value) {
            addCriterion("FARM_NAME <", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameLessThanOrEqualTo(String value) {
            addCriterion("FARM_NAME <=", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameLike(String value) {
            addCriterion("FARM_NAME like", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameNotLike(String value) {
            addCriterion("FARM_NAME not like", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameIn(List<String> values) {
            addCriterion("FARM_NAME in", values, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameNotIn(List<String> values) {
            addCriterion("FARM_NAME not in", values, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameBetween(String value1, String value2) {
            addCriterion("FARM_NAME between", value1, value2, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameNotBetween(String value1, String value2) {
            addCriterion("FARM_NAME not between", value1, value2, "farmName");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesIsNull() {
            addCriterion("NUMBER_OF_LINES is null");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesIsNotNull() {
            addCriterion("NUMBER_OF_LINES is not null");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesEqualTo(Integer value) {
            addCriterion("NUMBER_OF_LINES =", value, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesNotEqualTo(Integer value) {
            addCriterion("NUMBER_OF_LINES <>", value, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesGreaterThan(Integer value) {
            addCriterion("NUMBER_OF_LINES >", value, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_OF_LINES >=", value, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesLessThan(Integer value) {
            addCriterion("NUMBER_OF_LINES <", value, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesLessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_OF_LINES <=", value, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesIn(List<Integer> values) {
            addCriterion("NUMBER_OF_LINES in", values, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesNotIn(List<Integer> values) {
            addCriterion("NUMBER_OF_LINES not in", values, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_OF_LINES between", value1, value2, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfLinesNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_OF_LINES not between", value1, value2, "numberOfLines");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsIsNull() {
            addCriterion("NUMBER_OF_COLUMNS is null");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsIsNotNull() {
            addCriterion("NUMBER_OF_COLUMNS is not null");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsEqualTo(Integer value) {
            addCriterion("NUMBER_OF_COLUMNS =", value, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsNotEqualTo(Integer value) {
            addCriterion("NUMBER_OF_COLUMNS <>", value, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsGreaterThan(Integer value) {
            addCriterion("NUMBER_OF_COLUMNS >", value, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_OF_COLUMNS >=", value, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsLessThan(Integer value) {
            addCriterion("NUMBER_OF_COLUMNS <", value, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsLessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_OF_COLUMNS <=", value, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsIn(List<Integer> values) {
            addCriterion("NUMBER_OF_COLUMNS in", values, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsNotIn(List<Integer> values) {
            addCriterion("NUMBER_OF_COLUMNS not in", values, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_OF_COLUMNS between", value1, value2, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andNumberOfColumnsNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_OF_COLUMNS not between", value1, value2, "numberOfColumns");
            return (Criteria) this;
        }

        public Criteria andOpenDateIsNull() {
            addCriterion("OPEN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOpenDateIsNotNull() {
            addCriterion("OPEN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOpenDateEqualTo(Date value) {
            addCriterionForJDBCDate("OPEN_DATE =", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("OPEN_DATE <>", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateGreaterThan(Date value) {
            addCriterionForJDBCDate("OPEN_DATE >", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OPEN_DATE >=", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateLessThan(Date value) {
            addCriterionForJDBCDate("OPEN_DATE <", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OPEN_DATE <=", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateIn(List<Date> values) {
            addCriterionForJDBCDate("OPEN_DATE in", values, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("OPEN_DATE not in", values, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OPEN_DATE between", value1, value2, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OPEN_DATE not between", value1, value2, "openDate");
            return (Criteria) this;
        }

        public Criteria andTimeFromIsNull() {
            addCriterion("TIME_FROM is null");
            return (Criteria) this;
        }

        public Criteria andTimeFromIsNotNull() {
            addCriterion("TIME_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andTimeFromEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_FROM =", value, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeFromNotEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_FROM <>", value, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeFromGreaterThan(Date value) {
            addCriterionForJDBCDate("TIME_FROM >", value, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeFromGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_FROM >=", value, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeFromLessThan(Date value) {
            addCriterionForJDBCDate("TIME_FROM <", value, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeFromLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_FROM <=", value, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeFromIn(List<Date> values) {
            addCriterionForJDBCDate("TIME_FROM in", values, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeFromNotIn(List<Date> values) {
            addCriterionForJDBCDate("TIME_FROM not in", values, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeFromBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TIME_FROM between", value1, value2, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeFromNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TIME_FROM not between", value1, value2, "timeFrom");
            return (Criteria) this;
        }

        public Criteria andTimeToIsNull() {
            addCriterion("TIME_TO is null");
            return (Criteria) this;
        }

        public Criteria andTimeToIsNotNull() {
            addCriterion("TIME_TO is not null");
            return (Criteria) this;
        }

        public Criteria andTimeToEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_TO =", value, "timeTo");
            return (Criteria) this;
        }

        public Criteria andTimeToNotEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_TO <>", value, "timeTo");
            return (Criteria) this;
        }

        public Criteria andTimeToGreaterThan(Date value) {
            addCriterionForJDBCDate("TIME_TO >", value, "timeTo");
            return (Criteria) this;
        }

        public Criteria andTimeToGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_TO >=", value, "timeTo");
            return (Criteria) this;
        }

        public Criteria andTimeToLessThan(Date value) {
            addCriterionForJDBCDate("TIME_TO <", value, "timeTo");
            return (Criteria) this;
        }

        public Criteria andTimeToLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_TO <=", value, "timeTo");
            return (Criteria) this;
        }

        public Criteria andTimeToIn(List<Date> values) {
            addCriterionForJDBCDate("TIME_TO in", values, "timeTo");
            return (Criteria) this;
        }

        public Criteria andTimeToNotIn(List<Date> values) {
            addCriterionForJDBCDate("TIME_TO not in", values, "timeTo");
            return (Criteria) this;
        }

        public Criteria andTimeToBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TIME_TO between", value1, value2, "timeTo");
            return (Criteria) this;
        }

        public Criteria andTimeToNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TIME_TO not between", value1, value2, "timeTo");
            return (Criteria) this;
        }

        public Criteria andFarmLocationIsNull() {
            addCriterion("FARM_LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andFarmLocationIsNotNull() {
            addCriterion("FARM_LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andFarmLocationEqualTo(String value) {
            addCriterion("FARM_LOCATION =", value, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationNotEqualTo(String value) {
            addCriterion("FARM_LOCATION <>", value, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationGreaterThan(String value) {
            addCriterion("FARM_LOCATION >", value, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationGreaterThanOrEqualTo(String value) {
            addCriterion("FARM_LOCATION >=", value, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationLessThan(String value) {
            addCriterion("FARM_LOCATION <", value, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationLessThanOrEqualTo(String value) {
            addCriterion("FARM_LOCATION <=", value, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationLike(String value) {
            addCriterion("FARM_LOCATION like", value, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationNotLike(String value) {
            addCriterion("FARM_LOCATION not like", value, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationIn(List<String> values) {
            addCriterion("FARM_LOCATION in", values, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationNotIn(List<String> values) {
            addCriterion("FARM_LOCATION not in", values, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationBetween(String value1, String value2) {
            addCriterion("FARM_LOCATION between", value1, value2, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andFarmLocationNotBetween(String value1, String value2) {
            addCriterion("FARM_LOCATION not between", value1, value2, "farmLocation");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanIsNull() {
            addCriterion("SIZE_OF_PLAN is null");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanIsNotNull() {
            addCriterion("SIZE_OF_PLAN is not null");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanEqualTo(Double value) {
            addCriterion("SIZE_OF_PLAN =", value, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanNotEqualTo(Double value) {
            addCriterion("SIZE_OF_PLAN <>", value, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanGreaterThan(Double value) {
            addCriterion("SIZE_OF_PLAN >", value, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanGreaterThanOrEqualTo(Double value) {
            addCriterion("SIZE_OF_PLAN >=", value, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanLessThan(Double value) {
            addCriterion("SIZE_OF_PLAN <", value, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanLessThanOrEqualTo(Double value) {
            addCriterion("SIZE_OF_PLAN <=", value, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanIn(List<Double> values) {
            addCriterion("SIZE_OF_PLAN in", values, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanNotIn(List<Double> values) {
            addCriterion("SIZE_OF_PLAN not in", values, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanBetween(Double value1, Double value2) {
            addCriterion("SIZE_OF_PLAN between", value1, value2, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andSizeOfPlanNotBetween(Double value1, Double value2) {
            addCriterion("SIZE_OF_PLAN not between", value1, value2, "sizeOfPlan");
            return (Criteria) this;
        }

        public Criteria andClimateIsNull() {
            addCriterion("CLIMATE is null");
            return (Criteria) this;
        }

        public Criteria andClimateIsNotNull() {
            addCriterion("CLIMATE is not null");
            return (Criteria) this;
        }

        public Criteria andClimateEqualTo(String value) {
            addCriterion("CLIMATE =", value, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateNotEqualTo(String value) {
            addCriterion("CLIMATE <>", value, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateGreaterThan(String value) {
            addCriterion("CLIMATE >", value, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateGreaterThanOrEqualTo(String value) {
            addCriterion("CLIMATE >=", value, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateLessThan(String value) {
            addCriterion("CLIMATE <", value, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateLessThanOrEqualTo(String value) {
            addCriterion("CLIMATE <=", value, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateLike(String value) {
            addCriterion("CLIMATE like", value, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateNotLike(String value) {
            addCriterion("CLIMATE not like", value, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateIn(List<String> values) {
            addCriterion("CLIMATE in", values, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateNotIn(List<String> values) {
            addCriterion("CLIMATE not in", values, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateBetween(String value1, String value2) {
            addCriterion("CLIMATE between", value1, value2, "climate");
            return (Criteria) this;
        }

        public Criteria andClimateNotBetween(String value1, String value2) {
            addCriterion("CLIMATE not between", value1, value2, "climate");
            return (Criteria) this;
        }

        public Criteria andSoilIsNull() {
            addCriterion("SOIL is null");
            return (Criteria) this;
        }

        public Criteria andSoilIsNotNull() {
            addCriterion("SOIL is not null");
            return (Criteria) this;
        }

        public Criteria andSoilEqualTo(String value) {
            addCriterion("SOIL =", value, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilNotEqualTo(String value) {
            addCriterion("SOIL <>", value, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilGreaterThan(String value) {
            addCriterion("SOIL >", value, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilGreaterThanOrEqualTo(String value) {
            addCriterion("SOIL >=", value, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilLessThan(String value) {
            addCriterion("SOIL <", value, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilLessThanOrEqualTo(String value) {
            addCriterion("SOIL <=", value, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilLike(String value) {
            addCriterion("SOIL like", value, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilNotLike(String value) {
            addCriterion("SOIL not like", value, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilIn(List<String> values) {
            addCriterion("SOIL in", values, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilNotIn(List<String> values) {
            addCriterion("SOIL not in", values, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilBetween(String value1, String value2) {
            addCriterion("SOIL between", value1, value2, "soil");
            return (Criteria) this;
        }

        public Criteria andSoilNotBetween(String value1, String value2) {
            addCriterion("SOIL not between", value1, value2, "soil");
            return (Criteria) this;
        }

        public Criteria andEmailAddressIsNull() {
            addCriterion("EMAIL_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andEmailAddressIsNotNull() {
            addCriterion("EMAIL_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andEmailAddressEqualTo(String value) {
            addCriterion("EMAIL_ADDRESS =", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressNotEqualTo(String value) {
            addCriterion("EMAIL_ADDRESS <>", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressGreaterThan(String value) {
            addCriterion("EMAIL_ADDRESS >", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL_ADDRESS >=", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressLessThan(String value) {
            addCriterion("EMAIL_ADDRESS <", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressLessThanOrEqualTo(String value) {
            addCriterion("EMAIL_ADDRESS <=", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressLike(String value) {
            addCriterion("EMAIL_ADDRESS like", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressNotLike(String value) {
            addCriterion("EMAIL_ADDRESS not like", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressIn(List<String> values) {
            addCriterion("EMAIL_ADDRESS in", values, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressNotIn(List<String> values) {
            addCriterion("EMAIL_ADDRESS not in", values, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressBetween(String value1, String value2) {
            addCriterion("EMAIL_ADDRESS between", value1, value2, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressNotBetween(String value1, String value2) {
            addCriterion("EMAIL_ADDRESS not between", value1, value2, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("PHONE is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("PHONE =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("PHONE <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("PHONE >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("PHONE <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("PHONE <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("PHONE like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("PHONE not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("PHONE in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("PHONE not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("PHONE between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("PHONE not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andFaxIsNull() {
            addCriterion("FAX is null");
            return (Criteria) this;
        }

        public Criteria andFaxIsNotNull() {
            addCriterion("FAX is not null");
            return (Criteria) this;
        }

        public Criteria andFaxEqualTo(String value) {
            addCriterion("FAX =", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotEqualTo(String value) {
            addCriterion("FAX <>", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThan(String value) {
            addCriterion("FAX >", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThanOrEqualTo(String value) {
            addCriterion("FAX >=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThan(String value) {
            addCriterion("FAX <", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThanOrEqualTo(String value) {
            addCriterion("FAX <=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLike(String value) {
            addCriterion("FAX like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotLike(String value) {
            addCriterion("FAX not like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxIn(List<String> values) {
            addCriterion("FAX in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotIn(List<String> values) {
            addCriterion("FAX not in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxBetween(String value1, String value2) {
            addCriterion("FAX between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotBetween(String value1, String value2) {
            addCriterion("FAX not between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated do_not_delete_during_merge Tue May 16 09:30:26 ICT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IVB_M_FARM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}