package vn.bananavietnam.ict.common.db.model;

import java.util.Date;

public class IvbMTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.TASK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.TASK_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.WORKING_DETAILS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String workingDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.NOTE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.QUARANTINE_HANDLING_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Boolean quarantineHandlingFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.CHANGE_POINT_CODE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String changePointCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.TASK_ID
     *
     * @return the value of IVB_M_TASK.TASK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.TASK_ID
     *
     * @param taskId the value for IVB_M_TASK.TASK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.TASK_NAME
     *
     * @return the value of IVB_M_TASK.TASK_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.TASK_NAME
     *
     * @param taskName the value for IVB_M_TASK.TASK_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.WORKING_DETAILS
     *
     * @return the value of IVB_M_TASK.WORKING_DETAILS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getWorkingDetails() {
        return workingDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.WORKING_DETAILS
     *
     * @param workingDetails the value for IVB_M_TASK.WORKING_DETAILS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setWorkingDetails(String workingDetails) {
        this.workingDetails = workingDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.NOTE
     *
     * @return the value of IVB_M_TASK.NOTE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.NOTE
     *
     * @param note the value for IVB_M_TASK.NOTE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.QUARANTINE_HANDLING_FLAG
     *
     * @return the value of IVB_M_TASK.QUARANTINE_HANDLING_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Boolean getQuarantineHandlingFlag() {
        return quarantineHandlingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.QUARANTINE_HANDLING_FLAG
     *
     * @param quarantineHandlingFlag the value for IVB_M_TASK.QUARANTINE_HANDLING_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setQuarantineHandlingFlag(Boolean quarantineHandlingFlag) {
        this.quarantineHandlingFlag = quarantineHandlingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.CHANGE_POINT_CODE
     *
     * @return the value of IVB_M_TASK.CHANGE_POINT_CODE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getChangePointCode() {
        return changePointCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.CHANGE_POINT_CODE
     *
     * @param changePointCode the value for IVB_M_TASK.CHANGE_POINT_CODE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setChangePointCode(String changePointCode) {
        this.changePointCode = changePointCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.CREATE_USER_ID
     *
     * @return the value of IVB_M_TASK.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.CREATE_USER_ID
     *
     * @param createUserId the value for IVB_M_TASK.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.CREATE_DATE
     *
     * @return the value of IVB_M_TASK.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.CREATE_DATE
     *
     * @param createDate the value for IVB_M_TASK.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.UPDATE_USER_ID
     *
     * @return the value of IVB_M_TASK.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.UPDATE_USER_ID
     *
     * @param updateUserId the value for IVB_M_TASK.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.LAST_UPDATE_DATE
     *
     * @return the value of IVB_M_TASK.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for IVB_M_TASK.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.DELETE_FLAG
     *
     * @return the value of IVB_M_TASK.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.DELETE_FLAG
     *
     * @param deleteFlag the value for IVB_M_TASK.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}