package vn.bananavietnam.ict.common.db.model;

public class IvbMAccessAuthorizationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_ACCESS_AUTHORIZATION.ACCESS_AUTHORITY_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String accessAuthorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_ACCESS_AUTHORIZATION.SCREEN_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String screenId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_ACCESS_AUTHORIZATION.ACCESS_AUTHORITY_ID
     *
     * @return the value of IVB_M_ACCESS_AUTHORIZATION.ACCESS_AUTHORITY_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getAccessAuthorityId() {
        return accessAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_ACCESS_AUTHORIZATION.ACCESS_AUTHORITY_ID
     *
     * @param accessAuthorityId the value for IVB_M_ACCESS_AUTHORIZATION.ACCESS_AUTHORITY_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setAccessAuthorityId(String accessAuthorityId) {
        this.accessAuthorityId = accessAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_ACCESS_AUTHORIZATION.SCREEN_ID
     *
     * @return the value of IVB_M_ACCESS_AUTHORIZATION.SCREEN_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getScreenId() {
        return screenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_ACCESS_AUTHORIZATION.SCREEN_ID
     *
     * @param screenId the value for IVB_M_ACCESS_AUTHORIZATION.SCREEN_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setScreenId(String screenId) {
        this.screenId = screenId;
    }
}