package vn.bananavietnam.ict.common.db.model;

public class IvbMTaskKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.PROCESS_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    private String processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_TASK.TASK_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    private String taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.PROCESS_ID
     *
     * @return the value of IVB_M_TASK.PROCESS_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.PROCESS_ID
     *
     * @param processId the value for IVB_M_TASK.PROCESS_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    public void setProcessId(String processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_TASK.TASK_ID
     *
     * @return the value of IVB_M_TASK.TASK_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_TASK.TASK_ID
     *
     * @param taskId the value for IVB_M_TASK.TASK_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
}