package vn.bananavietnam.ict.common.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IvbMInformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public IvbMInformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFarmIdIsNull() {
            addCriterion("FARM_ID is null");
            return (Criteria) this;
        }

        public Criteria andFarmIdIsNotNull() {
            addCriterion("FARM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFarmIdEqualTo(String value) {
            addCriterion("FARM_ID =", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotEqualTo(String value) {
            addCriterion("FARM_ID <>", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdGreaterThan(String value) {
            addCriterion("FARM_ID >", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdGreaterThanOrEqualTo(String value) {
            addCriterion("FARM_ID >=", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdLessThan(String value) {
            addCriterion("FARM_ID <", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdLessThanOrEqualTo(String value) {
            addCriterion("FARM_ID <=", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdLike(String value) {
            addCriterion("FARM_ID like", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotLike(String value) {
            addCriterion("FARM_ID not like", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdIn(List<String> values) {
            addCriterion("FARM_ID in", values, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotIn(List<String> values) {
            addCriterion("FARM_ID not in", values, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdBetween(String value1, String value2) {
            addCriterion("FARM_ID between", value1, value2, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotBetween(String value1, String value2) {
            addCriterion("FARM_ID not between", value1, value2, "farmId");
            return (Criteria) this;
        }

        public Criteria andInforIdIsNull() {
            addCriterion("INFOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andInforIdIsNotNull() {
            addCriterion("INFOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInforIdEqualTo(String value) {
            addCriterion("INFOR_ID =", value, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdNotEqualTo(String value) {
            addCriterion("INFOR_ID <>", value, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdGreaterThan(String value) {
            addCriterion("INFOR_ID >", value, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdGreaterThanOrEqualTo(String value) {
            addCriterion("INFOR_ID >=", value, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdLessThan(String value) {
            addCriterion("INFOR_ID <", value, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdLessThanOrEqualTo(String value) {
            addCriterion("INFOR_ID <=", value, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdLike(String value) {
            addCriterion("INFOR_ID like", value, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdNotLike(String value) {
            addCriterion("INFOR_ID not like", value, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdIn(List<String> values) {
            addCriterion("INFOR_ID in", values, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdNotIn(List<String> values) {
            addCriterion("INFOR_ID not in", values, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdBetween(String value1, String value2) {
            addCriterion("INFOR_ID between", value1, value2, "inforId");
            return (Criteria) this;
        }

        public Criteria andInforIdNotBetween(String value1, String value2) {
            addCriterion("INFOR_ID not between", value1, value2, "inforId");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysIsNull() {
            addCriterion("DISPLAY_WAIT_DAYS is null");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysIsNotNull() {
            addCriterion("DISPLAY_WAIT_DAYS is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysEqualTo(Integer value) {
            addCriterion("DISPLAY_WAIT_DAYS =", value, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysNotEqualTo(Integer value) {
            addCriterion("DISPLAY_WAIT_DAYS <>", value, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysGreaterThan(Integer value) {
            addCriterion("DISPLAY_WAIT_DAYS >", value, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("DISPLAY_WAIT_DAYS >=", value, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysLessThan(Integer value) {
            addCriterion("DISPLAY_WAIT_DAYS <", value, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysLessThanOrEqualTo(Integer value) {
            addCriterion("DISPLAY_WAIT_DAYS <=", value, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysIn(List<Integer> values) {
            addCriterion("DISPLAY_WAIT_DAYS in", values, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysNotIn(List<Integer> values) {
            addCriterion("DISPLAY_WAIT_DAYS not in", values, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysBetween(Integer value1, Integer value2) {
            addCriterion("DISPLAY_WAIT_DAYS between", value1, value2, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayWaitDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("DISPLAY_WAIT_DAYS not between", value1, value2, "displayWaitDays");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodIsNull() {
            addCriterion("DISPLAY_PERIOD is null");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodIsNotNull() {
            addCriterion("DISPLAY_PERIOD is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodEqualTo(Integer value) {
            addCriterion("DISPLAY_PERIOD =", value, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodNotEqualTo(Integer value) {
            addCriterion("DISPLAY_PERIOD <>", value, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodGreaterThan(Integer value) {
            addCriterion("DISPLAY_PERIOD >", value, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("DISPLAY_PERIOD >=", value, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodLessThan(Integer value) {
            addCriterion("DISPLAY_PERIOD <", value, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("DISPLAY_PERIOD <=", value, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodIn(List<Integer> values) {
            addCriterion("DISPLAY_PERIOD in", values, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodNotIn(List<Integer> values) {
            addCriterion("DISPLAY_PERIOD not in", values, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodBetween(Integer value1, Integer value2) {
            addCriterion("DISPLAY_PERIOD between", value1, value2, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andDisplayPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("DISPLAY_PERIOD not between", value1, value2, "displayPeriod");
            return (Criteria) this;
        }

        public Criteria andInforIsNull() {
            addCriterion("INFOR is null");
            return (Criteria) this;
        }

        public Criteria andInforIsNotNull() {
            addCriterion("INFOR is not null");
            return (Criteria) this;
        }

        public Criteria andInforEqualTo(String value) {
            addCriterion("INFOR =", value, "infor");
            return (Criteria) this;
        }

        public Criteria andInforNotEqualTo(String value) {
            addCriterion("INFOR <>", value, "infor");
            return (Criteria) this;
        }

        public Criteria andInforGreaterThan(String value) {
            addCriterion("INFOR >", value, "infor");
            return (Criteria) this;
        }

        public Criteria andInforGreaterThanOrEqualTo(String value) {
            addCriterion("INFOR >=", value, "infor");
            return (Criteria) this;
        }

        public Criteria andInforLessThan(String value) {
            addCriterion("INFOR <", value, "infor");
            return (Criteria) this;
        }

        public Criteria andInforLessThanOrEqualTo(String value) {
            addCriterion("INFOR <=", value, "infor");
            return (Criteria) this;
        }

        public Criteria andInforLike(String value) {
            addCriterion("INFOR like", value, "infor");
            return (Criteria) this;
        }

        public Criteria andInforNotLike(String value) {
            addCriterion("INFOR not like", value, "infor");
            return (Criteria) this;
        }

        public Criteria andInforIn(List<String> values) {
            addCriterion("INFOR in", values, "infor");
            return (Criteria) this;
        }

        public Criteria andInforNotIn(List<String> values) {
            addCriterion("INFOR not in", values, "infor");
            return (Criteria) this;
        }

        public Criteria andInforBetween(String value1, String value2) {
            addCriterion("INFOR between", value1, value2, "infor");
            return (Criteria) this;
        }

        public Criteria andInforNotBetween(String value1, String value2) {
            addCriterion("INFOR not between", value1, value2, "infor");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 07 14:55:57 ICT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}