package vn.bananavietnam.ict.common.db.model;

import java.util.Date;

public class IvbMStatus extends IvbMStatusKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_STATUS.STATUS_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String statusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_STATUS.INFOR_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String inforId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_STATUS.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_STATUS.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_STATUS.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_STATUS.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_STATUS.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_STATUS.STATUS_NAME
     *
     * @return the value of IVB_M_STATUS.STATUS_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_STATUS.STATUS_NAME
     *
     * @param statusName the value for IVB_M_STATUS.STATUS_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_STATUS.INFOR_ID
     *
     * @return the value of IVB_M_STATUS.INFOR_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getInforId() {
        return inforId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_STATUS.INFOR_ID
     *
     * @param inforId the value for IVB_M_STATUS.INFOR_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setInforId(String inforId) {
        this.inforId = inforId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_STATUS.CREATE_USER_ID
     *
     * @return the value of IVB_M_STATUS.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_STATUS.CREATE_USER_ID
     *
     * @param createUserId the value for IVB_M_STATUS.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_STATUS.CREATE_DATE
     *
     * @return the value of IVB_M_STATUS.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_STATUS.CREATE_DATE
     *
     * @param createDate the value for IVB_M_STATUS.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_STATUS.UPDATE_USER_ID
     *
     * @return the value of IVB_M_STATUS.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_STATUS.UPDATE_USER_ID
     *
     * @param updateUserId the value for IVB_M_STATUS.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_STATUS.LAST_UPDATE_DATE
     *
     * @return the value of IVB_M_STATUS.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_STATUS.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for IVB_M_STATUS.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_STATUS.DELETE_FLAG
     *
     * @return the value of IVB_M_STATUS.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_STATUS.DELETE_FLAG
     *
     * @param deleteFlag the value for IVB_M_STATUS.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}