package vn.bananavietnam.ict.common.db.model;

import java.util.Date;

public class IvbMUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_USERS.USERS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_USERS.USERS_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String usersName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_USERS.PASSWORD
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_USERS.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_USERS.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_USERS.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_USERS.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_USERS.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_USERS.USERS_ID
     *
     * @return the value of IVB_M_USERS.USERS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_USERS.USERS_ID
     *
     * @param usersId the value for IVB_M_USERS.USERS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setUsersId(String usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_USERS.USERS_NAME
     *
     * @return the value of IVB_M_USERS.USERS_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getUsersName() {
        return usersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_USERS.USERS_NAME
     *
     * @param usersName the value for IVB_M_USERS.USERS_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setUsersName(String usersName) {
        this.usersName = usersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_USERS.PASSWORD
     *
     * @return the value of IVB_M_USERS.PASSWORD
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_USERS.PASSWORD
     *
     * @param password the value for IVB_M_USERS.PASSWORD
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_USERS.CREATE_USER_ID
     *
     * @return the value of IVB_M_USERS.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_USERS.CREATE_USER_ID
     *
     * @param createUserId the value for IVB_M_USERS.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_USERS.CREATE_DATE
     *
     * @return the value of IVB_M_USERS.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_USERS.CREATE_DATE
     *
     * @param createDate the value for IVB_M_USERS.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_USERS.UPDATE_USER_ID
     *
     * @return the value of IVB_M_USERS.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_USERS.UPDATE_USER_ID
     *
     * @param updateUserId the value for IVB_M_USERS.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_USERS.LAST_UPDATE_DATE
     *
     * @return the value of IVB_M_USERS.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_USERS.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for IVB_M_USERS.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_USERS.DELETE_FLAG
     *
     * @return the value of IVB_M_USERS.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_USERS.DELETE_FLAG
     *
     * @param deleteFlag the value for IVB_M_USERS.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}