package vn.bananavietnam.ict.common.db.model;

import java.util.Date;

public class IvbMDiseases {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.DISEASE_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String diseaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.DISEASE_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String diseaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.SYMPTOM
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String symptom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.HANDLING_METHOD
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String handlingMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.IMAGE_LINK_1
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String imageLink1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.IMAGE_LINK_2
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String imageLink2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.IMAGE_LINK_3
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String imageLink3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.IMAGE_LINK_4
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String imageLink4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.IMAGE_LINK_5
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String imageLink5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.NOTE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.DISEASE_ID
     *
     * @return the value of IVB_M_DISEASES.DISEASE_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.DISEASE_ID
     *
     * @param diseaseId the value for IVB_M_DISEASES.DISEASE_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setDiseaseId(String diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.DISEASE_NAME
     *
     * @return the value of IVB_M_DISEASES.DISEASE_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getDiseaseName() {
        return diseaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.DISEASE_NAME
     *
     * @param diseaseName the value for IVB_M_DISEASES.DISEASE_NAME
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.SYMPTOM
     *
     * @return the value of IVB_M_DISEASES.SYMPTOM
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.SYMPTOM
     *
     * @param symptom the value for IVB_M_DISEASES.SYMPTOM
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.HANDLING_METHOD
     *
     * @return the value of IVB_M_DISEASES.HANDLING_METHOD
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getHandlingMethod() {
        return handlingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.HANDLING_METHOD
     *
     * @param handlingMethod the value for IVB_M_DISEASES.HANDLING_METHOD
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setHandlingMethod(String handlingMethod) {
        this.handlingMethod = handlingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.IMAGE_LINK_1
     *
     * @return the value of IVB_M_DISEASES.IMAGE_LINK_1
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getImageLink1() {
        return imageLink1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.IMAGE_LINK_1
     *
     * @param imageLink1 the value for IVB_M_DISEASES.IMAGE_LINK_1
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setImageLink1(String imageLink1) {
        this.imageLink1 = imageLink1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.IMAGE_LINK_2
     *
     * @return the value of IVB_M_DISEASES.IMAGE_LINK_2
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getImageLink2() {
        return imageLink2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.IMAGE_LINK_2
     *
     * @param imageLink2 the value for IVB_M_DISEASES.IMAGE_LINK_2
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setImageLink2(String imageLink2) {
        this.imageLink2 = imageLink2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.IMAGE_LINK_3
     *
     * @return the value of IVB_M_DISEASES.IMAGE_LINK_3
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getImageLink3() {
        return imageLink3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.IMAGE_LINK_3
     *
     * @param imageLink3 the value for IVB_M_DISEASES.IMAGE_LINK_3
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setImageLink3(String imageLink3) {
        this.imageLink3 = imageLink3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.IMAGE_LINK_4
     *
     * @return the value of IVB_M_DISEASES.IMAGE_LINK_4
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getImageLink4() {
        return imageLink4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.IMAGE_LINK_4
     *
     * @param imageLink4 the value for IVB_M_DISEASES.IMAGE_LINK_4
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setImageLink4(String imageLink4) {
        this.imageLink4 = imageLink4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.IMAGE_LINK_5
     *
     * @return the value of IVB_M_DISEASES.IMAGE_LINK_5
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getImageLink5() {
        return imageLink5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.IMAGE_LINK_5
     *
     * @param imageLink5 the value for IVB_M_DISEASES.IMAGE_LINK_5
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setImageLink5(String imageLink5) {
        this.imageLink5 = imageLink5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.NOTE
     *
     * @return the value of IVB_M_DISEASES.NOTE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.NOTE
     *
     * @param note the value for IVB_M_DISEASES.NOTE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.CREATE_USER_ID
     *
     * @return the value of IVB_M_DISEASES.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.CREATE_USER_ID
     *
     * @param createUserId the value for IVB_M_DISEASES.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.CREATE_DATE
     *
     * @return the value of IVB_M_DISEASES.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.CREATE_DATE
     *
     * @param createDate the value for IVB_M_DISEASES.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.UPDATE_USER_ID
     *
     * @return the value of IVB_M_DISEASES.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.UPDATE_USER_ID
     *
     * @param updateUserId the value for IVB_M_DISEASES.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.LAST_UPDATE_DATE
     *
     * @return the value of IVB_M_DISEASES.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for IVB_M_DISEASES.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.DELETE_FLAG
     *
     * @return the value of IVB_M_DISEASES.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.DELETE_FLAG
     *
     * @param deleteFlag the value for IVB_M_DISEASES.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}