package vn.bananavietnam.ict.common.db.model;

public class IvbMDiseasesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.KIND_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    private String kindId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_DISEASES.DISEASE_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    private String diseaseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.KIND_ID
     *
     * @return the value of IVB_M_DISEASES.KIND_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    public String getKindId() {
        return kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.KIND_ID
     *
     * @param kindId the value for IVB_M_DISEASES.KIND_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    public void setKindId(String kindId) {
        this.kindId = kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_DISEASES.DISEASE_ID
     *
     * @return the value of IVB_M_DISEASES.DISEASE_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    public String getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_DISEASES.DISEASE_ID
     *
     * @param diseaseId the value for IVB_M_DISEASES.DISEASE_ID
     *
     * @mbggenerated Mon Mar 06 14:06:01 ICT 2017
     */
    public void setDiseaseId(String diseaseId) {
        this.diseaseId = diseaseId;
    }
}