package vn.bananavietnam.ict.common.db.model;

import java.util.Date;

public class IvbMFarm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.FARM_ID
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.FARM_NAME
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String farmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.NUMBER_OF_LINES
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private Integer numberOfLines;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.NUMBER_OF_COLUMNS
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private Integer numberOfColumns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.OPEN_DATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private Date openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.TIME_FROM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private Date timeFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.TIME_TO
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private Date timeTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.FARM_LOCATION
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String farmLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.SIZE_OF_PLAN
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private Double sizeOfPlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.CLIMATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String climate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.SOIL
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String soil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.EMAIL_ADDRESS
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String emailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.PHONE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.FAX
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.NOTE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.CREATE_USER_ID
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.CREATE_DATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.UPDATE_USER_ID
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_M_FARM.DELETE_FLAG
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.FARM_ID
     *
     * @return the value of IVB_M_FARM.FARM_ID
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.FARM_ID
     *
     * @param farmId the value for IVB_M_FARM.FARM_ID
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setFarmId(String farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.FARM_NAME
     *
     * @return the value of IVB_M_FARM.FARM_NAME
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getFarmName() {
        return farmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.FARM_NAME
     *
     * @param farmName the value for IVB_M_FARM.FARM_NAME
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setFarmName(String farmName) {
        this.farmName = farmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.NUMBER_OF_LINES
     *
     * @return the value of IVB_M_FARM.NUMBER_OF_LINES
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Integer getNumberOfLines() {
        return numberOfLines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.NUMBER_OF_LINES
     *
     * @param numberOfLines the value for IVB_M_FARM.NUMBER_OF_LINES
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setNumberOfLines(Integer numberOfLines) {
        this.numberOfLines = numberOfLines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.NUMBER_OF_COLUMNS
     *
     * @return the value of IVB_M_FARM.NUMBER_OF_COLUMNS
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Integer getNumberOfColumns() {
        return numberOfColumns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.NUMBER_OF_COLUMNS
     *
     * @param numberOfColumns the value for IVB_M_FARM.NUMBER_OF_COLUMNS
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setNumberOfColumns(Integer numberOfColumns) {
        this.numberOfColumns = numberOfColumns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.OPEN_DATE
     *
     * @return the value of IVB_M_FARM.OPEN_DATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Date getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.OPEN_DATE
     *
     * @param openDate the value for IVB_M_FARM.OPEN_DATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.TIME_FROM
     *
     * @return the value of IVB_M_FARM.TIME_FROM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Date getTimeFrom() {
        return timeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.TIME_FROM
     *
     * @param timeFrom the value for IVB_M_FARM.TIME_FROM
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setTimeFrom(Date timeFrom) {
        this.timeFrom = timeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.TIME_TO
     *
     * @return the value of IVB_M_FARM.TIME_TO
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Date getTimeTo() {
        return timeTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.TIME_TO
     *
     * @param timeTo the value for IVB_M_FARM.TIME_TO
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setTimeTo(Date timeTo) {
        this.timeTo = timeTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.FARM_LOCATION
     *
     * @return the value of IVB_M_FARM.FARM_LOCATION
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getFarmLocation() {
        return farmLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.FARM_LOCATION
     *
     * @param farmLocation the value for IVB_M_FARM.FARM_LOCATION
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setFarmLocation(String farmLocation) {
        this.farmLocation = farmLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.SIZE_OF_PLAN
     *
     * @return the value of IVB_M_FARM.SIZE_OF_PLAN
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Double getSizeOfPlan() {
        return sizeOfPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.SIZE_OF_PLAN
     *
     * @param sizeOfPlan the value for IVB_M_FARM.SIZE_OF_PLAN
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setSizeOfPlan(Double sizeOfPlan) {
        this.sizeOfPlan = sizeOfPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.CLIMATE
     *
     * @return the value of IVB_M_FARM.CLIMATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getClimate() {
        return climate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.CLIMATE
     *
     * @param climate the value for IVB_M_FARM.CLIMATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setClimate(String climate) {
        this.climate = climate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.SOIL
     *
     * @return the value of IVB_M_FARM.SOIL
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getSoil() {
        return soil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.SOIL
     *
     * @param soil the value for IVB_M_FARM.SOIL
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setSoil(String soil) {
        this.soil = soil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.EMAIL_ADDRESS
     *
     * @return the value of IVB_M_FARM.EMAIL_ADDRESS
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.EMAIL_ADDRESS
     *
     * @param emailAddress the value for IVB_M_FARM.EMAIL_ADDRESS
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.PHONE
     *
     * @return the value of IVB_M_FARM.PHONE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.PHONE
     *
     * @param phone the value for IVB_M_FARM.PHONE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.FAX
     *
     * @return the value of IVB_M_FARM.FAX
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.FAX
     *
     * @param fax the value for IVB_M_FARM.FAX
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.NOTE
     *
     * @return the value of IVB_M_FARM.NOTE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.NOTE
     *
     * @param note the value for IVB_M_FARM.NOTE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.CREATE_USER_ID
     *
     * @return the value of IVB_M_FARM.CREATE_USER_ID
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.CREATE_USER_ID
     *
     * @param createUserId the value for IVB_M_FARM.CREATE_USER_ID
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.CREATE_DATE
     *
     * @return the value of IVB_M_FARM.CREATE_DATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.CREATE_DATE
     *
     * @param createDate the value for IVB_M_FARM.CREATE_DATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.UPDATE_USER_ID
     *
     * @return the value of IVB_M_FARM.UPDATE_USER_ID
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.UPDATE_USER_ID
     *
     * @param updateUserId the value for IVB_M_FARM.UPDATE_USER_ID
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.LAST_UPDATE_DATE
     *
     * @return the value of IVB_M_FARM.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for IVB_M_FARM.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_M_FARM.DELETE_FLAG
     *
     * @return the value of IVB_M_FARM.DELETE_FLAG
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_M_FARM.DELETE_FLAG
     *
     * @param deleteFlag the value for IVB_M_FARM.DELETE_FLAG
     *
     * @mbggenerated Tue May 16 09:30:26 ICT 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}