package vn.bananavietnam.ict.common.db.model;

import java.util.Date;

public class IvbTCultivationResultSupplementaryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.AREA_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.BLOCK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String blockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LINE_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String lineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.COLUMN_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PREVIOUS_ROUND
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Boolean previousRound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.WORKING_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date workingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PROCESS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.TASK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.FARM_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.FARM_ID
     *
     * @param farmId the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setFarmId(String farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.AREA_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.AREA_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.AREA_ID
     *
     * @param areaId the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.AREA_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.BLOCK_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.BLOCK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.BLOCK_ID
     *
     * @param blockId the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.BLOCK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setBlockId(String blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LINE_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LINE_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LINE_ID
     *
     * @param lineId the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LINE_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setLineId(String lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.COLUMN_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.COLUMN_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.COLUMN_ID
     *
     * @param columnId the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.COLUMN_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setColumnId(String columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PREVIOUS_ROUND
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PREVIOUS_ROUND
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Boolean getPreviousRound() {
        return previousRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PREVIOUS_ROUND
     *
     * @param previousRound the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PREVIOUS_ROUND
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setPreviousRound(Boolean previousRound) {
        this.previousRound = previousRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.WORKING_DATE
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.WORKING_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getWorkingDate() {
        return workingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.WORKING_DATE
     *
     * @param workingDate the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.WORKING_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setWorkingDate(Date workingDate) {
        this.workingDate = workingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PROCESS_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PROCESS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PROCESS_ID
     *
     * @param processId the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.PROCESS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setProcessId(String processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.TASK_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.TASK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.TASK_ID
     *
     * @param taskId the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.TASK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
}