package vn.bananavietnam.ict.common.db.model;

import java.util.Date;

public class IvbTShippingControlKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_SHIPPING_CONTROL.FARM_ID
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    private String farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_SHIPPING_CONTROL.AREA_ID
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_SHIPPING_CONTROL.HARVEST_DATE
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    private Date harvestDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_SHIPPING_CONTROL.SHIPPING_DATE
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    private Date shippingDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_SHIPPING_CONTROL.FARM_ID
     *
     * @return the value of IVB_T_SHIPPING_CONTROL.FARM_ID
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    public String getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_SHIPPING_CONTROL.FARM_ID
     *
     * @param farmId the value for IVB_T_SHIPPING_CONTROL.FARM_ID
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    public void setFarmId(String farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_SHIPPING_CONTROL.AREA_ID
     *
     * @return the value of IVB_T_SHIPPING_CONTROL.AREA_ID
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_SHIPPING_CONTROL.AREA_ID
     *
     * @param areaId the value for IVB_T_SHIPPING_CONTROL.AREA_ID
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_SHIPPING_CONTROL.HARVEST_DATE
     *
     * @return the value of IVB_T_SHIPPING_CONTROL.HARVEST_DATE
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    public Date getHarvestDate() {
        return harvestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_SHIPPING_CONTROL.HARVEST_DATE
     *
     * @param harvestDate the value for IVB_T_SHIPPING_CONTROL.HARVEST_DATE
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    public void setHarvestDate(Date harvestDate) {
        this.harvestDate = harvestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_SHIPPING_CONTROL.SHIPPING_DATE
     *
     * @return the value of IVB_T_SHIPPING_CONTROL.SHIPPING_DATE
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    public Date getShippingDate() {
        return shippingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_SHIPPING_CONTROL.SHIPPING_DATE
     *
     * @param shippingDate the value for IVB_T_SHIPPING_CONTROL.SHIPPING_DATE
     *
     * @mbggenerated Mon Mar 13 10:31:31 ICT 2017
     */
    public void setShippingDate(Date shippingDate) {
        this.shippingDate = shippingDate;
    }
}