package vn.bananavietnam.ict.common.db.model;

import java.util.Date;

public class IvbTCultivationResultSupplementary extends IvbTCultivationResultSupplementaryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_1
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String imageLink1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_2
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String imageLink2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_3
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String imageLink3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_1
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_1
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getImageLink1() {
        return imageLink1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_1
     *
     * @param imageLink1 the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_1
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setImageLink1(String imageLink1) {
        this.imageLink1 = imageLink1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_2
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_2
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getImageLink2() {
        return imageLink2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_2
     *
     * @param imageLink2 the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_2
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setImageLink2(String imageLink2) {
        this.imageLink2 = imageLink2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_3
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_3
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getImageLink3() {
        return imageLink3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_3
     *
     * @param imageLink3 the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.IMAGE_LINK_3
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setImageLink3(String imageLink3) {
        this.imageLink3 = imageLink3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_USER_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_USER_ID
     *
     * @param createUserId the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_DATE
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_DATE
     *
     * @param createDate the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.UPDATE_USER_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.UPDATE_USER_ID
     *
     * @param updateUserId the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LAST_UPDATE_DATE
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.DELETE_FLAG
     *
     * @return the value of IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.DELETE_FLAG
     *
     * @param deleteFlag the value for IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}