package vn.bananavietnam.ict.common.db.model;

public class IvbTBlockHarvestSchedulesAmountKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.AREA_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.BLOCK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String blockId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.FARM_ID
     *
     * @return the value of IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.FARM_ID
     *
     * @param farmId the value for IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.FARM_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setFarmId(String farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.AREA_ID
     *
     * @return the value of IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.AREA_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.AREA_ID
     *
     * @param areaId the value for IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.AREA_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.BLOCK_ID
     *
     * @return the value of IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.BLOCK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.BLOCK_ID
     *
     * @param blockId the value for IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT.BLOCK_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setBlockId(String blockId) {
        this.blockId = blockId;
    }
}