package vn.bananavietnam.ict.common.db.model;

import java.util.Date;

public class IvbTCultivationResult extends IvbTCultivationResultKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT.BLOCK_WORK_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Boolean blockWorkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT.STATUS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT.NOTE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IVB_T_CULTIVATION_RESULT.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT.BLOCK_WORK_FLAG
     *
     * @return the value of IVB_T_CULTIVATION_RESULT.BLOCK_WORK_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Boolean getBlockWorkFlag() {
        return blockWorkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT.BLOCK_WORK_FLAG
     *
     * @param blockWorkFlag the value for IVB_T_CULTIVATION_RESULT.BLOCK_WORK_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setBlockWorkFlag(Boolean blockWorkFlag) {
        this.blockWorkFlag = blockWorkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT.STATUS_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT.STATUS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT.STATUS_ID
     *
     * @param statusId the value for IVB_T_CULTIVATION_RESULT.STATUS_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT.NOTE
     *
     * @return the value of IVB_T_CULTIVATION_RESULT.NOTE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT.NOTE
     *
     * @param note the value for IVB_T_CULTIVATION_RESULT.NOTE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT.CREATE_USER_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT.CREATE_USER_ID
     *
     * @param createUserId the value for IVB_T_CULTIVATION_RESULT.CREATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT.CREATE_DATE
     *
     * @return the value of IVB_T_CULTIVATION_RESULT.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT.CREATE_DATE
     *
     * @param createDate the value for IVB_T_CULTIVATION_RESULT.CREATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT.UPDATE_USER_ID
     *
     * @return the value of IVB_T_CULTIVATION_RESULT.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT.UPDATE_USER_ID
     *
     * @param updateUserId the value for IVB_T_CULTIVATION_RESULT.UPDATE_USER_ID
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT.LAST_UPDATE_DATE
     *
     * @return the value of IVB_T_CULTIVATION_RESULT.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for IVB_T_CULTIVATION_RESULT.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IVB_T_CULTIVATION_RESULT.DELETE_FLAG
     *
     * @return the value of IVB_T_CULTIVATION_RESULT.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IVB_T_CULTIVATION_RESULT.DELETE_FLAG
     *
     * @param deleteFlag the value for IVB_T_CULTIVATION_RESULT.DELETE_FLAG
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}