package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbMBlock;
import vn.bananavietnam.ict.common.db.model.IvbMBlockExample;
import vn.bananavietnam.ict.common.db.model.IvbMBlockKey;

public interface IvbMBlockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbMBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbMBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(IvbMBlockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbMBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbMBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbMBlock> selectByExample(IvbMBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbMBlock selectByPrimaryKey(IvbMBlockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbMBlock record, @Param("example") IvbMBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbMBlock record, @Param("example") IvbMBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbMBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_BLOCK
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbMBlock record);
}