package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbMPesticides;
import vn.bananavietnam.ict.common.db.model.IvbMPesticidesExample;

public interface IvbMPesticidesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbMPesticidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbMPesticidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(String pesticideId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbMPesticides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbMPesticides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbMPesticides> selectByExample(IvbMPesticidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbMPesticides selectByPrimaryKey(String pesticideId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbMPesticides record, @Param("example") IvbMPesticidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbMPesticides record, @Param("example") IvbMPesticidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbMPesticides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_PESTICIDES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbMPesticides record);
}