package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbMDiseases;
import vn.bananavietnam.ict.common.db.model.IvbMDiseasesExample;

public interface IvbMDiseasesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbMDiseasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbMDiseasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(String diseaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbMDiseases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbMDiseases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbMDiseases> selectByExample(IvbMDiseasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbMDiseases selectByPrimaryKey(String diseaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbMDiseases record, @Param("example") IvbMDiseasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbMDiseases record, @Param("example") IvbMDiseasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbMDiseases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_DISEASES
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbMDiseases record);
}