package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbMAuthorization;
import vn.bananavietnam.ict.common.db.model.IvbMAuthorizationExample;

public interface IvbMAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(String authorizationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbMAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbMAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbMAuthorization> selectByExample(IvbMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbMAuthorization selectByPrimaryKey(String authorizationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbMAuthorization record, @Param("example") IvbMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbMAuthorization record, @Param("example") IvbMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbMAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_AUTHORIZATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbMAuthorization record);
}