package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbMInformation;
import vn.bananavietnam.ict.common.db.model.IvbMInformationExample;
import vn.bananavietnam.ict.common.db.model.IvbMInformationKey;

public interface IvbMInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbMInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbMInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(IvbMInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbMInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbMInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbMInformation> selectByExample(IvbMInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbMInformation selectByPrimaryKey(IvbMInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbMInformation record, @Param("example") IvbMInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbMInformation record, @Param("example") IvbMInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbMInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_INFORMATION
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbMInformation record);
}