package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbMTreatmentOptions;
import vn.bananavietnam.ict.common.db.model.IvbMTreatmentOptionsExample;
import vn.bananavietnam.ict.common.db.model.IvbMTreatmentOptionsKey;

public interface IvbMTreatmentOptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbMTreatmentOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbMTreatmentOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(IvbMTreatmentOptionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbMTreatmentOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbMTreatmentOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbMTreatmentOptions> selectByExample(IvbMTreatmentOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbMTreatmentOptions selectByPrimaryKey(IvbMTreatmentOptionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbMTreatmentOptions record, @Param("example") IvbMTreatmentOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbMTreatmentOptions record, @Param("example") IvbMTreatmentOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbMTreatmentOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_TREATMENT_OPTIONS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbMTreatmentOptions record);
}