package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbMUsers;
import vn.bananavietnam.ict.common.db.model.IvbMUsersExample;

public interface IvbMUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(String usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbMUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbMUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbMUsers> selectByExample(IvbMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbMUsers selectByPrimaryKey(String usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbMUsers record, @Param("example") IvbMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbMUsers record, @Param("example") IvbMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbMUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_M_USERS
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbMUsers record);
}