package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbTCultivationResultSupplementary;
import vn.bananavietnam.ict.common.db.model.IvbTCultivationResultSupplementaryExample;
import vn.bananavietnam.ict.common.db.model.IvbTCultivationResultSupplementaryKey;

public interface IvbTCultivationResultSupplementaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbTCultivationResultSupplementaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbTCultivationResultSupplementaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(IvbTCultivationResultSupplementaryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbTCultivationResultSupplementary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbTCultivationResultSupplementary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbTCultivationResultSupplementary> selectByExample(IvbTCultivationResultSupplementaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbTCultivationResultSupplementary selectByPrimaryKey(IvbTCultivationResultSupplementaryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbTCultivationResultSupplementary record, @Param("example") IvbTCultivationResultSupplementaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbTCultivationResultSupplementary record, @Param("example") IvbTCultivationResultSupplementaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbTCultivationResultSupplementary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_CULTIVATION_RESULT_SUPPLEMENTARY
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbTCultivationResultSupplementary record);
}