package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbTShippingControl;
import vn.bananavietnam.ict.common.db.model.IvbTShippingControlExample;

public interface IvbTShippingControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbTShippingControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbTShippingControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(String shippingNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbTShippingControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbTShippingControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbTShippingControl> selectByExample(IvbTShippingControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbTShippingControl selectByPrimaryKey(String shippingNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbTShippingControl record, @Param("example") IvbTShippingControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbTShippingControl record, @Param("example") IvbTShippingControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbTShippingControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_SHIPPING_CONTROL
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbTShippingControl record);
}