package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbTBlockHarvestSchedulesAmount;
import vn.bananavietnam.ict.common.db.model.IvbTBlockHarvestSchedulesAmountExample;
import vn.bananavietnam.ict.common.db.model.IvbTBlockHarvestSchedulesAmountKey;

public interface IvbTBlockHarvestSchedulesAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbTBlockHarvestSchedulesAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbTBlockHarvestSchedulesAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(IvbTBlockHarvestSchedulesAmountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbTBlockHarvestSchedulesAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbTBlockHarvestSchedulesAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbTBlockHarvestSchedulesAmount> selectByExample(IvbTBlockHarvestSchedulesAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbTBlockHarvestSchedulesAmount selectByPrimaryKey(IvbTBlockHarvestSchedulesAmountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbTBlockHarvestSchedulesAmount record, @Param("example") IvbTBlockHarvestSchedulesAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbTBlockHarvestSchedulesAmount record, @Param("example") IvbTBlockHarvestSchedulesAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbTBlockHarvestSchedulesAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST_SCHEDULES_AMOUNT
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbTBlockHarvestSchedulesAmount record);
}