package vn.bananavietnam.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.bananavietnam.ict.common.db.model.IvbTBlockHarvest;
import vn.bananavietnam.ict.common.db.model.IvbTBlockHarvestExample;
import vn.bananavietnam.ict.common.db.model.IvbTBlockHarvestKey;

public interface IvbTBlockHarvestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int countByExample(IvbTBlockHarvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByExample(IvbTBlockHarvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int deleteByPrimaryKey(IvbTBlockHarvestKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insert(IvbTBlockHarvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int insertSelective(IvbTBlockHarvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    List<IvbTBlockHarvest> selectByExample(IvbTBlockHarvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    IvbTBlockHarvest selectByPrimaryKey(IvbTBlockHarvestKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExampleSelective(@Param("record") IvbTBlockHarvest record, @Param("example") IvbTBlockHarvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByExample(@Param("record") IvbTBlockHarvest record, @Param("example") IvbTBlockHarvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKeySelective(IvbTBlockHarvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IVB_T_BLOCK_HARVEST
     *
     * @mbggenerated Fri Apr 07 14:55:57 ICT 2017
     */
    int updateByPrimaryKey(IvbTBlockHarvest record);
}